server:
  port: 0
  servlet:
    context-path: /prices

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  datasource:
#    platform: postgres
#    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false
    # the following values must be added in the vault as following:
    # vault kv put secret/service-prices spring.datasource.username=service_prices
    # vault kv put secret/service-prices spring.datasource.password=srv-prcs
    username: root
    password: 123456
    initialization-mode: always
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: false
      hibernate:
        ddl-auto: create
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
#  zipkin:
#    baseUrl: http://127.0.0.1:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka